/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.daut.crypto.wealth;

import io.daut.crypto.wealth.core.*;
import io.daut.crypto.wealth.inbound.FortuneFile;
import io.daut.crypto.wealth.outbound.exchange.CryptoCompareClient;
import io.daut.crypto.wealth.outbound.exchange.CryptoCompareExchangeService;
import io.daut.crypto.wealth.outbound.printer.ConsolePrintService;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.net.http.HttpClient;
import java.util.List;

public class App {
    public final static String FILE_PATH = "./src/main/resources/bobs_crypto.txt";

    public static void main(String[] args) throws IOException {
        // OUTBOUND
        final HttpClient httpClient = HttpClient.newBuilder()
                .version(HttpClient.Version.HTTP_2)
                .build();
        final CryptoCompareClient cryptoCompareClient = new CryptoCompareClient(httpClient);
        final CryptoCompareExchangeService exchangeService = new CryptoCompareExchangeService(cryptoCompareClient);
        final ConsolePrintService printService = new ConsolePrintService();

        // CORE
        final WealthReportService wealthReportService = new WealthReportService(exchangeService, printService);

        // INBOUND
        final BufferedReader bufferedReader = new BufferedReader(new FileReader(FILE_PATH));
        final FortuneFile fortuneFile = new FortuneFile(bufferedReader);
        final List<Money> fortune = fortuneFile.parseFortune();

        // RUN
        wealthReportService.calculateWealth(fortune);
    }
}
