/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.daut.crypto.wealth;

//import io.daut.crypto.wealth.outbound.quote.CryptoCompareClient;
//import io.daut.crypto.wealth.outbound.quote.CryptoCompareExchangeService;
//import io.daut.crypto.wealth.outbound.print.ConsolePrintService;

import io.daut.crypto.wealth.core.ReportService;
import io.daut.crypto.wealth.inbound.ArgumentParser;
import io.daut.crypto.wealth.inbound.Arguments;
import io.daut.crypto.wealth.inbound.FileInput;
import io.daut.crypto.wealth.outbound.exchange.rate.crypto.compare.CryptoCompareClient;
import io.daut.crypto.wealth.outbound.exchange.rate.crypto.compare.CryptoCompareExchangeRateService;
import io.daut.crypto.wealth.outbound.print.console.console.ConsolePrintService;

import java.io.IOException;
import java.net.http.HttpClient;

public class App {
    public static void main(String[] args) throws IOException {
        // OUTBOUND
        final HttpClient httpClient = HttpClient.newBuilder()
                .version(HttpClient.Version.HTTP_2)
                .build();
        final CryptoCompareClient cryptoCompareClient = CryptoCompareClient.create(httpClient);
        final CryptoCompareExchangeRateService exchangeRateService = CryptoCompareExchangeRateService.create(cryptoCompareClient);
        final ConsolePrintService printService = new ConsolePrintService();

        // CORE
        final ReportService reportService = new ReportService(exchangeRateService, printService);

        // INBOUND
        final ArgumentParser argumentParser = ArgumentParser.create();
        final Arguments arguments = argumentParser.parseArguments(args);
        final FileInput fileInput = FileInput.create(reportService);

        // RUN
        fileInput.printReport(arguments);
    }
}
